### ISSUE TITLE
Add keep-alive call + garbage collection

### ISSUE THREAD

**Issue by ewencp** [sirikata/sirikata-cdn#4]
For transient data, we probably want some sort of keep alive call or a timeout to indicate when the data becomes invalid.  As a result, we'll be able to garbage collect that data periodically (or as soon as the individual asset goes past its expiration).  This will be necessary as models from the space server can become an extra storage burden.

**Comment by jterrace** [comment]
217b022 adds garbage collection for data that is no longer referenced. Garbage collection for the actual entries in the metadata table is easy - just mark the row with a TTL.

Eventually cleanup.py should be added as a periodic task with celerybeat, but I think it's fine to run manually for now since we aren't going to get a huge amount of data clogging up the database.

**Comment by ewencp** [comment]
What's the status of this? Is the TTL in there yet, and if so, can we add an optional parameter to API upload to support it?

**Comment by jterrace** [comment]
dff61866f5f adds TTL and a keepalive URL
